### ISSUE TITLE
node v6 seems to cause zero byting of files

### ISSUE THREAD

**Issue by lubomski** [jonycheung/deadsimple-less-watch-compiler#17]
upgrading node to v6.0.0 seems to cause the less compiler to produce zero-byte files; tried the native tests and running them produced following error:

```

> less-watch-compiler@1.2.3 test /Users/example/Downloads/deadsimple-less-watch-compiler-master
> cd tests && mocha



  lessWatchCompilerUtils Module API
    Should have the following API's
      walk()
        ✓ walk() function should be there
        1) walk() function should return an object of files 
      watchTree()
        ✓ watchTree() function should be there
        2) watchTree() function should complete and call a callback 
      compileCSS()
        ✓ compileCSS() function should be there
        ✓ should run the correct command with minified flag
      filterFiles()
        ✓ filterFiles() function should be there
        ✓ filterFiles() function should return "false" for allowed files
        ✓ filterFiles() function should return "true" for non-allowed files
      getDateTime()
        ✓ getDateTime() function should be there and has value


  8 passing (16ms)
  2 failing

  1) lessWatchCompilerUtils Module API Should have the following API's walk() walk() function should return an object of files :
     TypeError: path must be a string or Buffer
      at TypeError (native)
      at Object.fs.stat (fs.js:967:11)
      at Object.lessWatchCompilerUtilsModule.walk (/Users/example/Downloads/deadsimple-less-watch-compiler-master/lib/lessWatchCompilerUtils.js:27:18)
      at Context.<anonymous> (test.js:17:36)

  2) lessWatchCompilerUtils Module API Should have the following API's watchTree() watchTree() function should complete and call a callback :
     TypeError: path must be a string or Buffer
      at TypeError (native)
      at Object.fs.stat (fs.js:967:11)
      at Object.lessWatchCompilerUtilsModule.walk (/Users/example/Downloads/deadsimple-less-watch-compiler-master/lib/lessWatchCompilerUtils.js:27:18)
      at Object.lessWatchCompilerUtilsModule.watchTree (/Users/example/Downloads/deadsimple-less-watch-compiler-master/lib/lessWatchCompilerUtils.js:71:44)example      at Context.<anonymous> (test.js:35:36)



npm ERR! Test failed.  See above for more details.

```
Running OS X 10.11.4 / Mac Pro; reverting to Node 5.11.0 seems to allow it to work.

Anyone else encountered this issue?

**Comment by jonycheung** [comment]
I'll look into this.

**Comment by jonycheung** [comment]
I tested on my machine and it seems to work.
```
bash-3.2$ node -v
v6.1.0
bash-3.2$ npm test

> less-watch-compiler@1.2.3 test /Users/example/git/github/deadsimple-less-watch-compiler
> cd tests && mocha



  lessWatchCompilerUtils Module API
    Should have the following API's
      walk()
        ✓ walk() function should be there
        ✓ walk() function should return an object of files
      watchTree()
        ✓ watchTree() function should be there
        ✓ watchTree() function should complete and call a callback
      compileCSS()
        ✓ compileCSS() function should be there
        ✓ should run the correct command with minified flag
      filterFiles()
        ✓ filterFiles() function should be there
        ✓ filterFiles() function should return "false" for allowed files
        ✓ filterFiles() function should return "true" for non-allowed files
      getDateTime()
        ✓ getDateTime() function should be there and has value


  10 passing (26ms)
```

**Comment by lubomski** [comment]
@jonycheung i'm still getting the above error using node 6.1.0; i've downloaded the zip file and tried this on a vanilla OS X and the exact same error is reproducible there also. I'm not sure what the issue might be. Do you have any suggestions?
