### ISSUE TITLE
failing test

### ISSUE THREAD

**Issue by lubomski** [jonycheung/deadsimple-less-watch-compiler#19]
Apologies in advance for reporting this again. I've been looking into the previous error of the [zero-byting files](https://github.com/jonycheung/deadsimple-less-watch-compiler/issues/17) I was experiencing; the error was reproducible across multiple OS X and Linux machines. Have tested this in a vanilla OS X VM and the tests are still failing.

**Steps to reproduce:**

Install Node JS and NPM from http://www.nodejs.org (6.2.0)
download zip
cd into extracted dir
npm install -g less
npm install -g less-watch-compiler
npm test

**Experienced Results:**

```
lessWatchCompilerUtils Module API
    Should have the following API's
      walk()
        ✓ walk() function should be there
        1) walk() function should return an object of files 
      watchTree()
        ✓ watchTree() function should be there
        2) watchTree() function should complete and call a callback 
      compileCSS()
        ✓ compileCSS() function should be there
        ✓ should run the correct command with minified flag
      filterFiles()
        ✓ filterFiles() function should be there
        ✓ filterFiles() function should return "false" for allowed files
        ✓ filterFiles() function should return "true" for non-allowed files
      getDateTime()
        ✓ getDateTime() function should be there and has value


  8 passing (15ms)
  2 failing

  1) lessWatchCompilerUtils Module API Should have the following API's walk() walk() function should return an object of files :
     TypeError: path must be a string or Buffer
      at TypeError (native)
      at Object.fs.stat (fs.js:967:11)
      at Object.lessWatchCompilerUtilsModule.walk (/Users/example/Downloads/deadsimple-less-watch-compiler-master/lib/lessWatchCompilerUtils.js:27:18)
      at Context.<anonymous> (test.js:17:36)

  2) lessWatchCompilerUtils Module API Should have the following API's watchTree() watchTree() function should complete and call a callback :
     TypeError: path must be a string or Buffer
      at TypeError (native)
      at Object.fs.stat (fs.js:967:11)
      at Object.lessWatchCompilerUtilsModule.walk (/Users/example/Downloads/deadsimple-less-watch-compiler-master/lib/lessWatchCompilerUtils.js:27:18)
      at Object.lessWatchCompilerUtilsModule.watchTree (/Users/example/Downloads/deadsimple-less-watch-compiler-master/lib/lessWatchCompilerUtils.js:71:44)
      at Context.<anonymous> (test.js:35:36)



npm ERR! Test failed.  See above for more details.
```

I'm currently relying on Atom to compile my less for me. I've been scratching my head trying to figure out if i'm missing something obvious; the rollback to Node 5.11.0 still allows it to work.

**Comment by jonycheung** [comment]
Please take a look now. it should be fixed.
