### ISSUE TITLE
Error if less file has space in name

### ISSUE THREAD

**Issue by hatton** [jonycheung/deadsimple-less-watch-compiler#71]
Are you using the command line tool `less-watch-compiler`?
Yes

If you are using the command line tool, which version are you using (`less-watch-compiler --version` to find out)?

1.11.3

Is the issue reproducible after updating to the latest version (` npm update less-watch-compiler`)?

yes

Steps to reproduce:
1. Create a less file with the name "some styles.less", in a directory named "less"
1. `yarn less-watch-compiler less css`

Actual Results:

```
Watching directory for file changes.
{ Error: Command failed: lessc less\some\ styles.less css/some\ styles.css
lessc: ENOENT: no such file or directory, open 'C:\dev\b44\src\BloomBrowserUI\less\some'

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'lessc less\\some\\ styles.less css/some\\ styles.css' }
```

Expected Results:
- all valid files names should work.

**Comment by jonycheung** [comment]
`1.12.0` should _hopefully_ fix your problem
